# Generated by Django 3.1.6 on 2021-02-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semi_restful_tv_shows_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshows',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
