# Generated by Django 3.1.6 on 2021-03-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semi_restful_tv_shows_app', '0002_tvshows_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshows',
            name='releaseDate',
            field=models.DateField(blank=True),
        ),
    ]
