# Generated by Django 3.1.6 on 2021-03-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semi_restful_tv_shows_app', '0003_auto_20210301_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshows',
            name='releaseDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
